### ISSUE TITLE
Support for accounts that represent multiple agencies

### ISSUE THREAD

**Issue by bringhurst** [github/government.github.com#10]
I'm not sure how this would be implemented, but there are github accounts that are used by several agencies. For example, https://github.com/hpc is used by lanl.gov, llnl.gov, sandia.gov, ornl.gov, and others.

**Comment by bringhurst** [comment]
Pull request to add the hpc account without associating with an agency is at #14

**Comment by benbalter** [comment]
@fintler for now, at least, the list is simply a list of organizations, and does not make any assertion about the relationship between GitHub organizations and their agencies. As #14 implements, I think you handled things exactly right, but definitely something to keep in mind in the context of #75.
