### ISSUE TITLE
why the websites doesn't have any navbar

### ISSUE THREAD

**Issue by abhijain2003** [github/government.github.com#1093]
would be better if we shift the upper components to navbar, a more organized way to put data in websites and will be good in all device screen

https://user-images.githubusercontent.com/91718608/222970011-edddab1e-1e71-42c8-9bfc-4f0c1c3765a6.mp4

**Comment by psjnek** [comment]
<p align="center">This website already has a navbar:</p>

![image](https://user-images.githubusercontent.com/94064167/228936476-bfe42f98-d374-4e74-ba34-a0ad4dde42f3.png)

> will be good in all device screen

This website's navbar is already really responsive.

So, what would you like to change?

**Comment by mlinksva** [comment]
I don't think there's anything currently actionable, so closing.
