### ISSUE TITLE
Add section on Open Data Websites

### ISSUE THREAD

**Issue by StephenOTT** [github/government.github.com#110]
Add section on Open Data Websites and related repos.

Subsection/Partner section would contain list of repos on GitHub that leverage the specific Open data sources.

Potential stories would include apps, mobile apps, data scrapers, open data platforms like CKAN (http://ckan.org) and DKAN (https://drupal.org/project/dkan), visualization tools, news stories that occurred about the work being done, etc.

**Comment by miaguila0710** [comment]
Mi águila.Inc in PayPal

**Comment by mlinksva** [comment]
It looks like https://government.github.com/community/#civic_hackers has long included a lot of open data orgs. Other tools and news looks like it is out of scope for the site. Thanks for opening this 6 years ago!
