### ISSUE TITLE
Set up locally instructions failing

### ISSUE THREAD

**Issue by ras44** [github/government.github.com#1168]
Thank you for building this repo!

I'm working through the **Set up locally** instructions at: 

https://github.com/github/government.github.com#to-set-up-locally

On ubuntu, which matches the `.github/workflows/build.yml` I can build and serve with the following:

```
sudo apt update
# following https://jekyllrb.com/docs/installation/ubuntu/
sudo apt-get install ruby-full build-essential zlib1g-dev
echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
gem install jekyll bundler
# install node.js
sudo apt install nodejs
# following To Set up Locally instructions
git clone https://github.com/github/government.github.com.git
cd government.github.com
script/bootstrap
script/server
```

If I've understood things correctly, the missing requirement from the instructions is the installation of a JavaScript runtime.

Not sure if there might also be an option to use the docker image that is pulled by the GitHub actions process?

```
/usr/bin/docker pull ghcr.io/actions/jekyll-build-pages:v1.0.7
```

Thanks so much for your work and guidance 🙏

**Comment by mlinksva** [comment]
This was addressed by #1169
