### ISSUE TITLE
uuid issue

### ISSUE THREAD

**Issue by l0spendej0s** [github/government.github.com#1282]
i searched "Thermodynamo Axe" and "Vicious Battleaxe" both had the same uuid listed: 9b6a4ab2-323b-4030-89ab-030252bb6214

**Comment by ripgoobrielle** [comment]
found more, daggers this time:
9b6a4ab2-323b-4030-89ab-030252bb6214   Cold Snap
9b6a4ab2-323b-4030-89ab-030252bb6214   Dolor Amarus
9b6a4ab2-323b-4030-89ab-030252bb6214   Dread Iron Dagger
9b6a4ab2-323b-4030-89ab-030252bb6214   Gleamdance Dagger
9b6a4ab2-323b-4030-89ab-030252bb6214   Sussur Dagger
 
81764c3c-c7a9-49a7-b145-d31ffd5aebe1   Rhapsody 
81764c3c-c7a9-49a7-b145-d31ffd5aebe1   Stillmaker

**Comment by ripgoobrielle** [comment]
i found that anything less than legendary ranking tends to be wrong as i stopped after two great axes:
86e7e503-a225-4b48-819e-2e24de1f904a   The Undead Bane *
86e7e503-a225-4b48-819e-2e24de1f904a   Very Heavy Greataxe *
but these legendaries are marked as the same as well:
81764c3c-c7a9-49a7-b145-d31ffd5aebe1   Hellfire Greataxe
81764c3c-c7a9-49a7-b145-d31ffd5aebe1   Sethan

**Comment by ripgoobrielle** [comment]
every single +1 and +2 is the same:
4cd41c74-9c86-4233-922e-4db5bc750df5   Battleaxe +1
71191c11-966f-4c19-b4ee-eb36d31c4944   Battleaxe +2
4cd41c74-9c86-4233-922e-4db5bc750df5   Dagger +1
71191c11-966f-4c19-b4ee-eb36d31c4944   Dagger +2
4cd41c74-9c86-4233-922e-4db5bc750df5   Flail +1
71191c11-966f-4c19-b4ee-eb36d31c4944   Flail +2
4cd41c74-9c86-4233-922e-4db5bc750df5   Glaive +1
71191c11-966f-4c19-b4ee-eb36d31c4944   Glaive +2
4cd41c74-9c86-4233-922e-4db5bc750df5   Greataxe +1
71191c11-966f-4c19-b4ee-eb36d31c4944   Greataxe +2
4cd41c74-9c86-4233-922e-4db5bc750df5   Greatclub +1
71191c11-966f-4c19-b4ee-eb36d31c4944   Greatclub +2
4cd41c74-9c86-4233-922e-4db5bc750df5   Greatsword +1
71191c11-966f-4c19-b4ee-eb36d31c4944   Greatsword +2

this shit took me too long to notice. i want to hop in and figure out what these codes actually are, but i just want to keep making a file full of codes for myself. just feels like a waste of time when most of the uuids coming up are the same as other items

**Comment by ripgoobrielle** [comment]
a lot of legendaries are the same and i just feel stupid, like i am doing something severely wrong
