### ISSUE TITLE
Reduce http requests and redirects

### ISSUE THREAD

**Issue by XhmikosR** [github/government.github.com#151]
Initially mentioned here  https://github.com/github/government.github.com/pull/127#issuecomment-27144625.

There are so many http requests ~320. And most of them are because of redirects from github to gravatar.

Now since most organizations in `#orgs` are hidden with `overflow: hidden;`, they shouldn't be in index.html in the first place IMHO.

Another approach would be to use a css sprite but that won't be so flexible.

**Comment by XhmikosR** [comment]
I experimented a little bit with this but I can't make it work...

``` html
      <div class="the-orgs">
    {% for type_hash in site.organizations limit:60 %}
      {% for org in type_hash[1] %}
        <div class="organization">
          <a href="https://github.com/{{ org }}" title="{{ org }}">
            <img class="avatar" src="https://github.com/{{ org }}.png" width="80" height="80" alt="{{ org }}"/>
          </a>
        </div>
      {% endfor %}
    {% endfor %}
      </div> <!-- class="the-orgs" -->
    </div> <!-- id="orgs" -->
```

I used `limit: 60` since we have 5 rows with 12 columns each.

There must be some way to do this but I can't figure it out yet.

**Comment by XhmikosR** [comment]
If I do this it works...

``` html
    {% for type_hash in site.organizations | limit: 10 %}
      {% for org in type_hash[1] %}
```

@benbalter: what do you think of this approach? I just don't get what `10` is supposed to be in reality. I would expect `60` to work too.

**Comment by jlord** [comment]
@XhmikosR I'd prefer not to have it a sprite -- I like the fact that you can click on the avatars from that page and that it's not just a flat image. 

That being said, once we launched, a lot more orgs were added than we started out with originally; we definitely don't need to be getting all of their avatars for index.html.

I'm ok with reducing the number of avatars we get for index.html so long as we maintain the look it has currently and get enough extra to give the "full bleed" effect of the graphic.

**Comment by XhmikosR** [comment]
@jlord: you can still have a sprite and clickable avatars. But that would require extra work to maintain. Performance-Wise is the best solution though.

I will make a pull request later when I understand why limit:60 doesn't work.

**Comment by jlord** [comment]
@XhmikosR exactly - the sprite is not ideal and performance is not enough of (or a) goal of this site so I'm not leaning in the _extra-work-to-maintain_ direction as the performance currently isn't limiting the usability of the site. 

If we can shave some requests off by having it pull fewer avatars :thumbsup:

**Comment by XhmikosR** [comment]
We totally agree.

I found [more](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#for-loops) info about limit, looking into it now.

**Comment by XhmikosR** [comment]
I have some results here

``` diff
 index.html | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/index.html b/index.html
index 2439212..3bded2c 100644
--- a/index.html
+++ b/index.html
@@ -50,13 +50,18 @@ title: GitHub and Government
   <div class="container">
     <div id="orgs">
       <div class="the-orgs">
+    {% assign count = "0" %}
     {% for type_hash in site.organizations %}
       {% for org in type_hash[1] %}
+        {% capture diff %}{{ count | minus:87 }}{% endcapture %}
+        {% unless diff contains '-' %}
         <div class="organization">
           <a href="https://github.com/{{ org }}" title="{{ org }}">
             <img class="avatar" src="https://github.com/{{ org }}.png" width="80" height="80" alt="{{ org }}"/>
           </a>
         </div>
+        {% endunless %}
+        {% capture count %}{{ count | plus:1 }}{% endcapture %}
       {% endfor %}
     {% endfor %}
       </div> <!-- class="the-orgs" -->

```

Still hacky though.

**Comment by XhmikosR** [comment]
This seems cleaner; we just specify the number of orgs to show

``` diff
 index.html | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/index.html b/index.html
index 2439212..dd52f54 100644
--- a/index.html
+++ b/index.html
@@ -50,13 +50,18 @@ title: GitHub and Government
   <div class="container">
     <div id="orgs">
       <div class="the-orgs">
+    {% assign count = "0" %}
     {% for type_hash in site.organizations %}
       {% for org in type_hash[1] %}
+        {% capture diff %}{{ count | minus:60 }}{% endcapture %}
+        {% if diff contains '-' %}
         <div class="organization">
           <a href="https://github.com/{{ org }}" title="{{ org }}">
             <img class="avatar" src="https://github.com/{{ org }}.png" width="80" height="80" alt="{{ org }}"/>
           </a>
         </div>
+        {% endif %}
+        {% capture count %}{{ count | plus:1 }}{% endcapture %}
       {% endfor %}
     {% endfor %}
       </div> <!-- class="the-orgs" -->

```
