### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Teddy95** [github/government.github.com#157]
Sorry, but where can I find a license for scripts and fonts? :)

**Comment by Teddy95** [comment]
Thank you :)

**Comment by afeld** [comment]
The [scripts](https://github.com/github/government.github.com/tree/gh-pages/assets/js) are third-party so you need to go by their license - @cameronmcefee, maybe we should include a note about the Octicons?

**Comment by Teddy95** [comment]
I think it would be useful.

**Comment by cameronmcefee** [comment]
@Teddy95 Octicons are not technically publicly shipped (still working out the kinks), so they're provided as-is with no guarantee of support. You're welcome to use them if you like, but with the knowledge that they are not officially supported until they've been publicly shipped if or when that happens.

As they change often and this specific collection is intended for the web, installing them locally is likely to cause issues when they become out of date from the official GitHub set of Octicons (I've often run into this issue myself). Install at your own risk. Should newer GitHub icons start appearing as squares or blank on GitHub sites, your problem will likely be a conflict of fonts which can be resolved by uninstalling the font locally.

**Comment by Teddy95** [comment]
Okay, thank you very much for your quick and detailed answer.

**Comment by afeld** [comment]
Presumably the GitHub logo usage (even as an Octicon) falls under the same terms of use as https://github.com/logos.
