### ISSUE TITLE
Move organizations to `_data` directory

### ISSUE THREAD

**Issue by XhmikosR** [github/government.github.com#162]
https://github.com/mojombo/jekyll/blob/master/site/docs/datafiles.md

This seems like a more flexible solution for government.github.com compared to having to edit `_config.yml` which is becoming huge anyway.

Maybe having a yml file for each country would make the situation much cleaner.

**Comment by nschonni** [comment]
Related to #139 and #75

**Comment by benbalter** [comment]
The feature's [not yet stable](http://jekyllrb.com/news/2013/10/28/jekyll-1-3-0-rc1-released/), let alone on Pages, but something to discuss depending on the outcome of #75. Biggest pushback would be complexity.

**Comment by XhmikosR** [comment]
@benbalter: I didn't notice this was a new feature to be honest. But it does sound like the best compromise for government.github.com. I guess we should wait a little bit more. :)
