### ISSUE TITLE
Any interest in a shoutout for GitHub Training?

### ISSUE THREAD

**Issue by brntbeer** [github/government.github.com#167]
Just curious on the team as well as communities feelings about a mention of GitHub Training being available for government bodies if they're interested.

Some text and message similar to: 

> Interested in Training? We have a team at GitHub specifically for that. Contact training@github.com to start the discussion today!

Full with professor_octocat_v2 or something.

Thoughts?

**Comment by benbalter** [comment]
Where were you think this would fit in the site?

**Comment by brntbeer** [comment]
under `/community` page explicitly? Maybe the "More Resources" box on the side panel of `/features`, `/community`, and `/about` pages. Bottom of the front page orrrrrrrr under FAQ?

**Comment by brntbeer** [comment]
It'd be rad if it was somewhere easily viewable and not hidden, but not IN YOUR FACE.

**Comment by nschonni** [comment]
What about under the "Learn More" section of the footer :wink:

**Comment by benbalter** [comment]
@brntbeer we also have https://github.com/government/best-practices/blob/master/docs/resources.md, which could use some love, and to which we could probably link out to better.

**Comment by brntbeer** [comment]
yeah for sure. A link to http://training.github.com/contact/ may be best, so as to not confuse people with a second `mailto:` as well.
