### ISSUE TITLE
Community grid not displaying correctly

### ISSUE THREAD

**Issue by jlord** [github/government.github.com#171]
I'm guessing during one of the merges of the updates to the css/bootstrap/whatnots that something got changed that created this bug in the display of orgs on /community:

![screen shot 2013-11-04 at 11 52 18 pm](https://f.cloud.github.com/assets/1305617/1469908/88f5678e-45ac-11e3-9601-ec3981951a34.png)

There shouldn't be almost blank rows. It's happening if a type-block ends up in the last position of a row.

Will try and fix it in the morning (it's late here!).

**Comment by jlord** [comment]
@XhmikosR I tracked down where this problem began -- it was the merge of your commit [a5c05bde7fe1478efcdcc1aa3cc7a2951255ac36](https://github.com/github/government.github.com/commit/a5c05bde7fe1478efcdcc1aa3cc7a2951255ac36). As of the previous commit [92989cd351e3576fdaf841fd7fcd3639352087ce](https://github.com/github/government.github.com/commit/92989cd351e3576fdaf841fd7fcd3639352087ce) the  community grid was displaying correctly (all full rows). 

Will you have a look at it?

**Comment by XhmikosR** [comment]
I can have a look, sure.

**Comment by XhmikosR** [comment]
See #172.

PS. It would be nice if someone merged my remaining PRs so that I can make a new one about the http requests reduction.
