### ISSUE TITLE
Change the minimum IE supported for government.github.com

### ISSUE THREAD

**Issue by XhmikosR** [github/government.github.com#193]
IE 8 works sort of ok, apart for the logo image. IE7 looks awfully broken.

I suggest we follow the latest html5 boilerplate and make IE 8 the minimum supported IE.

I can make a PR later for this.

**Comment by XhmikosR** [comment]
After PR #229 is in, IE8 should work fine. But IE7, which is what is [now](https://github.com/github/government.github.com/blob/gh-pages/_includes/header.html#L23) shown as the minimum IE version, is still wrong. `display: inline-block`, octicons etc don't work with IE7.

**Comment by benbalter** [comment]
@XhmikosR is this still an issue? If so, what can we do to fix it?

**Comment by XhmikosR** [comment]
@benbalter: I don't think this applies anymore being that you use jQuery 2.x which doesn't work for IE < 9. Also, generally GitHub doesn't work on IE < 9 (or even 10?) so it's OK to close this.
