### ISSUE TITLE
Submitting story using the prose editor

### ISSUE THREAD

**Issue by klemmj** [github/government.github.com#196]
I followed the directions on http://government.github.com/submit/ for submitting a story:

Simply open the Prose editor and start typing. It’s really that easy. When you’re done, hit submit, and track your story’s progress as it’s added.

It's not clear the submission worked.  Can you confirm?

Thanks,

Juli Klemm

**Comment by klemmj** [comment]
The story is entitled "Opening up Informatics for Cancer Research".

**Comment by nschonni** [comment]
Your story is here #195
