### ISSUE TITLE
typo in instructions at http://government.github.com/community/

### ISSUE THREAD

**Issue by talllguy** [github/government.github.com#214]
Small typo in the instructions heading of the [community page](http://government.github.com/community/). One of the bullets looks like:
- In your forked version, click the branch dropdown and in the “**Fnid** or create a branch…” field, create a new branch (for example, “adding myagencyname”).

Notice **Fnid**, which should be Find.

**Comment by afeld** [comment]
Good catch, thanks!

**Comment by talllguy** [comment]
Happy to help!
