### ISSUE TITLE
Zen the zen, pls

### ISSUE THREAD

**Issue by ErieMeyer** [github/government.github.com#276]
Hi! In zen mode, even in fullscreen, there's still a sad scrollbar an no way (I can find) to reduce font. Very hard to visually ID linebreaks.

I can haz expanding margins?

![image](https://cloud.githubusercontent.com/assets/1626026/3059545/d6e76208-e1ec-11e3-923a-89657f3a870e.png)

**Comment by benbalter** [comment]
@ErieMeyer Thanks for the feedback. Is this specific to governemnt.github.com or GitHub in general? If the latter, mind submitting the above to support@github.com so we can get it in front of our front-end team?
