### ISSUE TITLE
Link out to government showcase

### ISSUE THREAD

**Issue by benbalter** [github/government.github.com#293]
Via @adamjacobbecker, we should link out to [the government app showcase](https://github.com/showcases/government) from government.github.com in a big way.

Mirroring the features "learn more" link, thinking it'd make the most sense to add it below the "how to use GitHub" section. Don't :heart: the copy, but something like:

![screen shot 2014-07-29 at 9 50 31 am](https://cloud.githubusercontent.com/assets/282759/3735726/5334545a-1727-11e4-8efc-505df7319860.png)

@jlord, any suggestions?

**Comment by jlord** [comment]
:thumbsup: Totally should be linking to that -- here comes a PR!
