### ISSUE TITLE
Resize Featured org images

### ISSUE THREAD

**Issue by nschonni** [github/government.github.com#303]
Currently the [feature org images](https://github.com/github/government.github.com/tree/gh-pages/assets/img/featured-orgs) are being set with an inline attribute to 80px wide, but the payload for the page is pretty larg since these images are >300KB each :frowning:

**Comment by theaverageguy** [comment]
Can I work on this?

**Comment by benbalter** [comment]
@yash14123 thanks for offering. We'd love your help (with this, or anything else)! 

@nschonni did you have any thought son how to fix this?

To note, the avatars are now being loaded via https://github.com/benbalter/jekyll-avatar (which in essence, is just a shared HTML template)

**Comment by nschonni** [comment]
@benbalter it looks like the new library is requesting the correctly sized images rather than resizing the images on the client side
