### ISSUE TITLE
Avatar downloads on the Community page

### ISSUE THREAD

**Issue by nschonni** [github/government.github.com#304]
Adding the `s=` query parameter would shrink down the size of the images downloaded, but that doesn't work unless you resolve the github user content url first. Ex: `https://avatars3.githubusercontent.com/u/1297909`
![30px Avatar](https://avatars3.githubusercontent.com/u/1297909?v=2&amp;s=30) `?v=2&amp;s=30`
![100px Avatar](https://avatars3.githubusercontent.com/u/1297909?v=2&amp;s=100) `?v=2&amp;s=100`

Since passing the format `https://github.com/nschonni.png?s=30` doesn't pass through the query params, maybe you can look up on your side to see if there is a trick to get it to request the right size.

**Comment by benbalter** [comment]
This has been fixed by using https://github.com/benbalter/jekyll-avatar.
