### ISSUE TITLE
Responsiveness lost around 672×640

### ISSUE THREAD

**Issue by sahilbabbar** [github/government.github.com#348]
Hi,

The website looses its responsive nature around 672×640. Few portions of text go out of the screen.

**Comment by sahilbabbar** [comment]
Kindly take required action. If the problem is accepted then, I may start working on this.

**Comment by benbalter** [comment]
@sahilbabbar I'm not able to recreate the issue. Are you able to post a screenshot? Alternatively, are you able to submit a pull request to update the CSS to fix it?

**Comment by sahilbabbar** [comment]
Its working fine.
