### ISSUE TITLE
Convert user account to organization account

### ISSUE THREAD

**Issue by benbalter** [github/government.github.com#368]
Doing a little clean up of the government organizations list at [government.github.com/community](https://government.github.com/community) and I noticed the follow government "organizations" are really GitHub users.

Being a GitHub organization (rather than a user) provides government organizations with lots of advantages like team-based access permissions, unlimited owners, admins, and collaborators, the ability to audit 2FA status, and access to business-oriented plans.

Think about it like the difference between your personal account on Facebook, and having a Facebook page. For more information see [What's the difference between user and organization accounts?](https://help.github.com/articles/what-s-the-difference-between-user-and-organization-accounts/). 

If your name is listed below, and you're a government organization, I'd strongly encourage you to [Converting your user into an organization](https://help.github.com/articles/converting-a-user-into-an-organization/). It takes seconds, and won't break existing URLs or disrupt developers' workflows.

Ideally, we'd only like government organizations to be listed on  [government.github.com/community](https://government.github.com/community). If you have any questions, or don't want your name listed for some reason, please feel free to reply here, or contact me directly at government@github.com. :smile:

---

@2ek
@carersbeta
@edelegationen
@educationdatainitiative
@foreignassistance
@gemeenteboekel
@gemeentedewoldenhoogeveen
@gemeenteedamvolendam
@gemeentehoogezandsappemeer
@gemeentekoggenland
@gemeentelingewaard
@gemeentelochem
@gemeentemontferland
@gemeentenunspeet
@gemeenterheden
@gemeentetynaarlo
@gemeenteurk
@gemeenteutrecht
@gemeenteveere
@gemeentewaalwijk
@gemeenteweststellingwerf
@iens-velsen
@minienm
@ncbitools
@ouropendata
@sfgov
@state-hiu

**Comment by NCBITools** [comment]
Hi Ben – @NCBI is the organization. @Ncbitools is a user we created, so that as people come and go, we have a constant user.
