### ISSUE TITLE
no access permission to '/'

### ISSUE THREAD

**Issue by wayneiny** [github/government.github.com#421]
Hi I followed the instruction in READMD.md and finished running ./server. It instructed me to open localhost:4000/ but when I did that, it just gave me error that no access permission to '/'. Could you please explain this is happening? Thank you.

**Comment by sonalkr132** [comment]
I was not able to duplicate your issue. Can you please post server log? 

You might find [#1293](https://github.com/jekyll/jekyll/issues/1293) useful.

**Comment by wayneiny** [comment]
Yes it's the same problem, but I don't know how to solve it. Thanks for
replying.

**Comment by benbalter** [comment]
> and finished running ./server

Are you running `./server` from the `./scripts`/ directory, or `script/server/` from the root directory?
