### ISSUE TITLE
Add commenting system for posts

### ISSUE THREAD

**Issue by nschonni** [github/government.github.com#44]
Maybe Disqus or something similar?

**Comment by afeld** [comment]
I have mixed feelings about this.  More tech-savvy readers will be able to submit corrections, additional resources, etc. via Pull Requests and Issues, so I feel like a comment box will simply invite less-constructive feedback.  If people have meaningful suggestions about how a particular policy or whatever could be handled differently, those are more appropriate for those individual repos anyway.

**Comment by benbalter** [comment]
Thanks @nschonni. Closing since the stories have been moved to the peer group page.
