### ISSUE TITLE
Work around symlink issue

### ISSUE THREAD

**Issue by XhmikosR** [github/government.github.com#452]
```
C:\Users\xmr\Desktop\government.github.com>ruby -v && gem -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
2.5.2

C:\Users\xmr\Desktop\government.github.com>bundle exec jekyll s
Configuration file: C:/Users/xmr/Desktop/government.github.com/_config.yml
            Source: C:/Users/xmr/Desktop/government.github.com
       Destination: C:/Users/xmr/Desktop/government.github.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    File to import not found or unreadable: bootstrap/stylesheet
s/bootstrap. Load path: C:/Users/xmr/Desktop/government.github.com/_sass on line 2
jekyll 3.0.3 | Error:  File to import not found or unreadable: bootstrap/stylesheets/bootstrap.
Load path: C:/Users/xmr/Desktop/government.github.com/_sass on line 2
```

Or if anyone has any other solution, please let me know.

/CC @benbalter

**Comment by XhmikosR** [comment]
So, any chance we could work around this issue? I want to clean up more styles and it's hard to do it via the browser only :/

**Comment by benbalter** [comment]
> So, any chance we could work around this issue? I want to clean up more styles and it's hard to do it via the browser only :/

@XhmikosR Thanks again for all the recent pull requests, we (and the community) really appreciate them. To be completely transparent, I wanted to let you know that this issue may not get addressed immediately. It's no reflection on you or your contributions (they're great). There are lots of competing priorities at GItHub, and micro-optimizations like consolidating style sheets or optimizing images, while beneficial, often are forced to take a back seat to more user-centric initiatives. (I'm just one person! :smile_cat:)

**Comment by leog** [comment]
@XhmikosR I figured out how to workaround this issue for the @Standards homepage which uses the same theme as this page. You can see it on the https://github.com/Standards/standards.github.io repository.

**Comment by jbjonesjr** [comment]
site has been updated, OBE
