### ISSUE TITLE
where to put government-initiated GitHub orgs?

### ISSUE THREAD

**Issue by afeld** [github/government.github.com#467]
There are a few GitHub organizations that are government-initiated, but they aren't tied to a single government entity per se...not sure where they should go. Ideas?

- @DistributedOpenUnifiedGovernmentNetwork
- @fisma-ready
- @openopps
- @eregs
- @uspki
- @opencontrol

**Comment by benbalter** [comment]
Civic hackers?

**Comment by leahbannon** [comment]
That sounds like a good place for openopps to me. I'm not familiar with the other projects.

**Comment by jbjonesjr** [comment]
back here, i feel like uspki could fall under government though, as could fisma-ready. Not familiar enough with the rest. ¯\_(ツ)_/¯

Closing this out, but happy to continue this. I'd love to be more explicit about where to put things, it sort of a `feel` thing at the moment.
