### ISSUE TITLE
community page should more a list style

### ISSUE THREAD

**Issue by muescha** [github/government.github.com#54]
http://government.github.com/community/ should be more a list styel with the name of the organization additionaly - not only the logo

it gives a better overview

PS: for accessibilty is list also better

**Comment by jlord** [comment]
@muescha I agree there should be another iteration on the /community page. We're learning there are so many more orgs and divisions than we imagined. 

I definitely want the page to useful and accessible so am going to let some more pull requests from orgs come in to get a better sense of the breadth of orgs and iterate on making the page better. 

For now, if you hover over the image, it will show the org name in the tooltip.

**Comment by nschonni** [comment]
@jlord :+1: for the alt tag, but could it pull the GitHub `fullname` property instead?

**Comment by benbalter** [comment]
>  for the alt tag, but could it pull the GitHub fullname property instead?

Right now, the only information we have is the org name, via `_config.yml`, and I'd love to keep it that simple, if possible.

> should be more a list styel with the name of the organization additionaly - not only the logo

We definitely can and should continue to improve the experience. For insight, part of the original vision was the effect of having a wall of logos to show just how large the community is.

**Comment by nschonni** [comment]
> Right now, the only information we have is the org name, via _config.yml, and I'd love to keep it that simple, if possible.

KISS :smile:, not sure how hard it would be to use the GitHub API to get the info when _config.yml gets converted to the organization JSON file

**Comment by muescha** [comment]
just now the github userpage dont give much information about the organisation

**Comment by rmw** [comment]
I agree it'd be helpful to have more info about the organization - since they are adding into YAML anyway, we could just change the format to something like:

```
organizations:
  -
     github_name: awesomegov
     full_name: Super Awesome Gov
     location: Super Awesome Country
     short_description: blah
```

That way they can add if they want and we'll just show what's available.  It wouldn't be too much to convert the existing yaml to this either. OR we could check if the val is a hash or not and if not, only show the name.

Happy to take this on if people are cool with it.

**Comment by nschonni** [comment]
@rmw I started something like that in #139, but feel free to take that base (or not) and improve upon it!
