### ISSUE TITLE
Alphabetize, other chores should run monthly, open new PRs automatically

### ISSUE THREAD

**Issue by jbjonesjr** [github/government.github.com#601]
Currently, the alphabetize script (https://github.com/github/government.github.com/blob/gh-pages/script/alphabetize)  is run manually to clean up the ordering of Organizations in the various data files. (Example: https://github.com/github/government.github.com/pull/582). A couple problems with this:

1. Why do work that a robot 🤖 can do?
2. Since this repo is widely maintained, it's impossible to guarantee that these changes won't create pretty annoying conflicts for other PRs. 

Getting these to a near automated fashion would be really cool.

I'd held off merging a bunch of [open PRs](https://github.com/github/government.github.com/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20updated%3A%3E2017-07-01) in hopes that I'd get time to work on a solution for this, but alas I have not. So, I figure I'll crowd source this to see if anyone has any ideas or fancy the execution.

## Note
I'd love to use [probot](https://probot.github.io) as the framework for these operations (it's what it was made for), but it's currently a node app and is expecting j/s scripts. Since I try to do as little with YAML as possible 😉 , this task was never exciting enough to get my attention for very long, and why it floundered. It should be pretty easy as `js-yaml` and basic JS functions should map pretty cleanly.

By opening this issue, this will be a reminder to me to eventually get to it too, so no pressure.

**Comment by nschonni** [comment]
Seems like the cron jobs on Travis-CI would fit the bill https://docs.travis-ci.com/user/cron-jobs/

**Comment by miaguila0710** [comment]
U think this about me???

**Comment by nschonni** [comment]
Looks like GitHub Actions supports this now too https://help.github.com/en/articles/workflow-syntax-for-github-actions#onschedule

**Comment by nschonni** [comment]
Fixed with https://github.com/github/government.github.com/pull/825
