### ISSUE TITLE
Organisation logos are shown twice in the "Join the Revolution" section

### ISSUE THREAD

**Issue by ilyapopov** [github/government.github.com#637]
![screenshot-2017-12-18 github and government](https://user-images.githubusercontent.com/1054514/34116526-2d74901e-e419-11e7-9723-c96d980c3383.png)

**Comment by alex-page** [comment]
The scrolling on the page is also broken due to the second group of logos not being wrapped in the `overflow:hidden;` div.

**Comment by jbjonesjr** [comment]
yep. fixed in #679
