### ISSUE TITLE
improve page load speed

### ISSUE THREAD

**Issue by afeld** [github/government.github.com#664]
The page is getting slow to load, which is (I believe) almost entirely due to the number of avatars being loaded. I would suggest doing a lazy load of the images. There are a number of JavaScript plugins to facilitate this. Happy to take a pass at it, if interested!

**Comment by jbjonesjr** [comment]
@afeld i understand you have a fix for this in one of the jekyll upstream gems? (https://github.com/benbalter/jekyll-avatar/issues/16).  Once @benbalter cuts a release, we can update the gemfile here.

**Comment by afeld** [comment]
Also we have to wait for it to be updated in GitHub Pages.

**Comment by jbjonesjr** [comment]
ph, good point. i assumed it was in a site gem, but it is in the pages infrastructure. 👍

**Comment by afeld** [comment]
Now waiting on https://github.com/github/pages-gem/pull/573.

**Comment by jbjonesjr** [comment]
Now waiting on https://github.com/github/pages-gem/pull/576
