### ISSUE TITLE
Universities?

### ISSUE THREAD

**Issue by patricktokeeffe** [github/government.github.com#667]
I noticed none are listed. Our research group within the university is state funded but we also compete for federal and third-party grants. Would it make sense to be listed as a state agency? Or is another category a better approach? 

Or maybe they are excluded for some reason?

**Comment by jbjonesjr** [comment]
@patricktokeeffe This is a conversation that comes up from time to time. The Government section is for full-govt orgs. Now, if your research group is basically a Fee Funded Research Org (like the US DOE National Labs for example), then it can belong in this section.

If not, it could make sense for them to fall in the research section. Feel free to reopen if you still have questions.
