### ISSUE TITLE
Move contribute box to sidebar of story page

### ISSUE THREAD

**Issue by benbalter** [github/government.github.com#69]
Placed similar to the "more resources" box on supporting pages.

![screen_shot_2013-10-16_at_11 53 41_am](https://f.cloud.github.com/assets/282759/1345726/61ce5912-3694-11e3-8f6f-557d4bcee777.png)

Tried to do it, but couldn't quite get it right.

Halp?

**Comment by jlord** [comment]
Np! I'm on it!
