### ISSUE TITLE
TODO: Configure caching for fast building on CI

### ISSUE THREAD

**Issue by jbjonesjr** [github/government.github.com#750]
Description and details here: https://github.com/gjtorikian/html-proofer#configuring-caching and https://github.com/gjtorikian/html-proofer#caching-with-travis

**Comment by jbjonesjr** [comment]
Also worth reviewing additional html-proofer options, as many have likely been added since we first started using it. Lots of opportunity for improvement

**Comment by nschonni** [comment]
Can probably close now that Travis isn't being used anymore

**Comment by mlinksva** [comment]
I'm not sure it's worth doing but I'd guess it still could be with https://github.com/actions/cache
