### ISSUE TITLE
Ensure entries are alphabetized build failed

### ISSUE THREAD

**Issue by ugd-mg** [github/government.github.com#837]
Hello there, I'm new here. We are from Madagascar. We want to put our organization on https://government.github.com/community/. When we edit and pull [governments.yml](https://github.com/github/government.github.com/blob/gh-pages/_data/governments.yml) we get this
![image](https://user-images.githubusercontent.com/70996381/93870280-a3872c80-fcd5-11ea-8d13-f4f4cee91ad1.png)

Please! Someone can help us? Thank you in advance

**Comment by nschonni** [comment]
If you look at the failure details it shows you in the diff what the format it is expecting. In some cases you have trailing space that is causing a diff and others it's missing lines around the section

**Comment by ugd-mg** [comment]
It works, I create an Organization and submit it. Thank you guys. I'm waiting for validation
