### ISSUE TITLE
Translations of site

### ISSUE THREAD

**Issue by nschonni** [github/government.github.com#84]
Since this is highlighting international work, it may be a good idea to look into crowdsourcing some translations

**Comment by benbalter** [comment]
All for that. Just need to figure out the best way. See https://github.com/github/choosealicense.com/issues/68 for some insight.

@parkr, any (new) thoughts here? Perhaps the `_data` folder?

**Comment by parkr** [comment]
Yep, or a new custom liquid tag like `{% localize lang KEY %}`.
