### ISSUE TITLE
Invalid user causing pull request checks to fail

### ISSUE THREAD

**Issue by dougwaldron** [github/government.github.com#863]
Pull request #862 failed because unrelated user `@bcdevexchange` does not exist.

**Comment by mlinksva** [comment]
It appears the main repo in that org may have been moved to https://github.com/bcgov/digital_marketplace/ and bcgov is already cataloged here.

**Comment by mlinksva** [comment]
I'm wrong, they're related, but the bcdevexchange org may now be ExchangeBC.
