### ISSUE TITLE
Add rotator to blog post categories

### ISSUE THREAD

**Issue by nschonni** [github/government.github.com#87]
This would mitigate the concerns raised by @jlord here https://github.com/github/government.github.com/pull/36#issuecomment-26461855 about stories getting pushed off the front page too quickly.

**Comment by theaverageguy** [comment]
Would like to take this up.

**Comment by benbalter** [comment]
@yash14123 thanks for volunteering. We actually moved the stories to http://government.github.io/best-practices since this issue originally opened.
