### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by WavingCatDevs** [github/government.github.com#883]
Broken Heroku links in the images below 

![Image](https://user-images.githubusercontent.com/69034430/132541680-2fc7c703-1dc9-4c57-a93b-7ab3102533e8.PNG)

![Image](https://user-images.githubusercontent.com/69034430/132541740-7aaec047-3b77-4c5c-a3a7-d8a2bae8221b.PNG)

![Image](https://user-images.githubusercontent.com/69034430/132541829-4d9a45bf-8c5a-409e-b855-5cf7f82d3cd8.PNG)

**Comment by KamalSinghKhanna** [comment]
hey! I would like to fix this. can you tell me that where these links point.

**Comment by WavingCatDevs** [comment]
> hey! I would like to fix this. can you tell me that where these links point.

https://government-community.githubapp.com/

**Comment by KamalSinghKhanna** [comment]
@WavingCatDevs how can we solve this?

**Comment by WavingCatDevs** [comment]
> @WavingCatDevs how can we solve this?

There's no way unless the github staff does

**Comment by mlinksva** [comment]
These links work now!

**Comment by WavingCatDevs** [comment]
> These links work now!

Thank you
